VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Class1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function ŠÖ”1() As String
    ŠÖ”1 = "ŒÄ‚Î‚ê‚½‚æ"
End Function

Public Function ŠÖ”2() As String
    ŠÖ”2 = "ŒÄ‚Î‚ê‚½‚æ2"
End Function

Public Function ŠÖ”3(ByVal val As Long) As Long
    ŠÖ”3 = val * 10
End Function
